### PR TITLE
Fixed n00b error forgetting to rename the class for delete and put!

### PR DESCRIPTION
**Pull request by MattiusAscentMS**
Sorry I left this in a state unable to compile for Android! That's fixed now, about to test Android so I'll merge any other fixes in when I come across them!

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi, I spotted those as well and fixed them, see #17. Perhaps you need to update your fork?

Thanks!

**Comment by MattiusAscentMS** [comment]
Ahh Thanks! Will do!

On Fri, Jun 10, 2016 at 10:31 AM, Eddy Verplugin <notifications@github.com>
wrote:

> Hi, I spotted those as well and fixed them, see #17
> <https://github.com/Telerik-Verified-Plugins/SecureHTTP/pull/17>. Perhaps
> you need to update your fork?
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Telerik-Verified-Plugins/SecureHTTP/pull/21#issuecomment-225137342>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKXSxfWHiJA0Zq-ATyF5Qmz88KItw02bks5qKS8BgaJpZM4Iyxcq>
> .
>



-- 

*Matthew Hartley*

Developer & Technologist


Tel  +44 77 342 64 377 <07734264377>

Email  matt@evergreen-life.co.uk

Web   www.evergreen-life.co.uk

[image:
https://lh5.googleusercontent.com/gxbugEQ5jZDaWwkM2zVegGgxCuvb9C1CfVIBYTERBv5hYT1lyAyy_HFxTlUFEKoGAJlwS2HgMSXQNS2ECikCSSvD3W7V7r9Zw7fb8_o_pml28DQtYxxg4xl910LYvTYu_WswTzSI]
<https://appsto.re/gb/wyT39.i>   [image:
https://lh6.googleusercontent.com/j-DwwExSTOBh1hVlL8_9usAm9Yg2ITCiWjsfMxbzBqiHqkfcTbonIAwQtdvZXKr-WLJC60Q173DFcI2ROoJc6iTSAuAOxMZUWlIgvDSkAguqRB8fw2iCtJg_xVoM_eAz41gpaSkM]
<https://play.google.com/store/apps/details?id=com.ascent.phr&hl=en_GB>

<http://facebook.com/evergreenlifeuk> <http://pinterest.com/live_evergreen>
<http://twitter.com/live_evergreen>

*Important Notice*
*This **communication is from Ascent Health Solutions(Registration No
9484935) trading as Evergreen Life. It is incorporated in England and Wales
at registered office The Edge Business Centre, Clowes Street, Manchester.
M3 5NA, United Kingdom.*


*This communication contains information which is confidential and may also
be privileged. It is for the exclusive use of the intended recipient(s). If
you are not the intended recipient(s), please (1) notify *
*admin@evergreen-life.co.uk* <admin@evergreen-life.co.uk>

*  by forwarding this email and delete all copies from your system and (2)
note that disclosure, distribution, copying or use of this communication is
strictly prohibited. Email communications cannot be guaranteed to be secure
or free from error or viruses. To the extent permitted by law, Evergreen
Life does not accept any liability for use of or reliance on the contents
of this email by any person save by the intended recipient(s). Opinions,
conclusions and other information in this email which have not been
delivered by way of the business of Ascent Health Solutions Ltd are neither
given nor endorsed by it.*

**Comment by MattiusAscentMS** [comment]
Hi, there are a couple more fixes in this request now, seems I missed an if statement off too! I've tested Android now though and I'm happy that its working!

I also updated my fork :)

**Comment by EddyVerbruggen** [comment]
Thanks, if you're happy I am :)

**Comment by EddyVerbruggen** [comment]
Added you as a committer, so if you spot anything else please go ahead 👍

**Comment by MattiusAscentMS** [comment]
Thanks, our app will be using this plugin quite heavily so any improvements
I put in I will push back to the community!!

Cheers,
Mattius

On Tue, Jun 14, 2016 at 10:16 AM, Eddy Verplugin notifications@github.com
wrote:

> Added you as a committer, so if you spot anything else please go ahead 👍
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Telerik-Verified-Plugins/SecureHTTP/pull/21#issuecomment-225824937,
> or mute the thread
> https://github.com/notifications/unsubscribe/AKXSxVxr1IY-e6vkblir6jvlj7x_s5yGks5qLnFngaJpZM4Iyxcq
> .

## 

_Matthew Hartley_

Developer & Technologist

Tel  +44 77 342 64 377 <07734264377>

Email  matt@evergreen-life.co.uk

Web   www.evergreen-life.co.uk

[image:
https://lh5.googleusercontent.com/gxbugEQ5jZDaWwkM2zVegGgxCuvb9C1CfVIBYTERBv5hYT1lyAyy_HFxTlUFEKoGAJlwS2HgMSXQNS2ECikCSSvD3W7V7r9Zw7fb8_o_pml28DQtYxxg4xl910LYvTYu_WswTzSI]
https://appsto.re/gb/wyT39.i   [image:
https://lh6.googleusercontent.com/j-DwwExSTOBh1hVlL8_9usAm9Yg2ITCiWjsfMxbzBqiHqkfcTbonIAwQtdvZXKr-WLJC60Q173DFcI2ROoJc6iTSAuAOxMZUWlIgvDSkAguqRB8fw2iCtJg_xVoM_eAz41gpaSkM]
https://play.google.com/store/apps/details?id=com.ascent.phr&hl=en_GB

http://facebook.com/evergreenlifeuk http://pinterest.com/live_evergreen
http://twitter.com/live_evergreen

_Important Notice_
_This *_communication is from Ascent Health Solutions(Registration No
9484935) trading as Evergreen Life. It is incorporated in England and Wales
at registered office The Edge Business Centre, Clowes Street, Manchester.
M3 5NA, United Kingdom.*

_This communication contains information which is confidential and may also
be privileged. It is for the exclusive use of the intended recipient(s). If
you are not the intended recipient(s), please (1) notify *
*admin@evergreen-life.co.uk_ admin@evergreen-life.co.uk
-  by forwarding this email and delete all copies from your system and (2)
  note that disclosure, distribution, copying or use of this communication is
  strictly prohibited. Email communications cannot be guaranteed to be secure
  or free from error or viruses. To the extent permitted by law, Evergreen
  Life does not accept any liability for use of or reliance on the contents
  of this email by any person save by the intended recipient(s). Opinions,
  conclusions and other information in this email which have not been
  delivered by way of the business of Ascent Health Solutions Ltd are neither
  given nor endorsed by it.*

**Pull request merged**
